ktor:
  development: ${DEVELOPMENT:-false}
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

database:
  driver: ${DRIVER}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
  port: ${DB_PORT}

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
